apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasknew-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flasknew
  template:
    metadata:
      labels:
        app: flasknew
    spec:
      containers:
        - name: flasknew
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          ports:
            - containerPort: 5000

